### ISSUE TITLE
Esup Pay mise à jour en 1.1.0 (erreur)

### ISSUE THREAD

**Issue by devwald** [EsupPortail/esup-pay#3]
Bonjour,

Je viens de mettre à jour Esup Pay en 1.1.0 (j'étais en 1.0.3) et je rencontre l'erreur suivante :

> "Erreur interne"

Dans les logs, je n'ai que ceci :

> "2018-06-21 13:30:03,032 [ajp-nio-8009-exec-4] INFO  org.esupportail.pay.security.PayLdapAuthoritiesPopulator - Roles from ldap groups for wald_f : [ROLE_954K0, ROLE_EMAEVAL-GI, ROLE_SI, ROLE_CRI-APPLI-ENT-WEB, ROLE_RE2, ROLE_DSI-DEV, ROLE_999, ROLE_CRI-APPLI-GESTION, ROLE_DSI-APPLI, ROLE_DSI-ALL, ROLE_954, ROLE_EMAEVAL-GT]
> 2018-06-21 13:30:03,064 [ajp-nio-8009-exec-4] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERROR: column payevt0_.dble_montant_max does not exist
>   Position: 29"

Je pense qu'il faut que je redémarre l'application avec src/main/resources/META-INF/persistence.xml positionné à create mais je risque de perdre toutes mes transactions.

Par conséquent, quelle serait la solution ?

Merci d'avance.

Cdt.

**Comment by vbonamy** [comment]
Bonjour,
Il faudrait mettre update dans persistence.xml, ce qui permet de laisser
hibernate mettre à joru le schéma de la base de données (tout en conservant
les donnéeés).
Bien cordialement,
Vincent Bonamy.


2018-06-25 15:49 GMT+02:00 devwald <notifications@github.com>:

**Comment by devwald** [comment]
Bonjour,

Merci de votre réponse mais c'était déjà le cas : 

`<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
<persistence-unit name="persistenceUnit" transaction-type="RESOURCE_LOCAL">
        <provider>org.hibernate.ejb.HibernatePersistence</provider>
        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.PostgreSQLDialect"/>
            
            <property name="hibernate.hbm2ddl.auto" value="update"/>
            <property name="hibernate.ejb.naming_strategy" value="org.hibernate.cfg.ImprovedNamingStrategy"/>
            <property name="hibernate.connection.charSet" value="UTF-8"/>
            
            
            
        </properties>
    </persistence-unit>
</persistence>
`
Cdt.

**Comment by vbonamy** [comment]
Du coup peut-être que l'utilisateur utilisé sur la base (et donc par
hibernate) n'a pas le droit de modifier le schéma ?
On retrouve peut-être des logs indiquant ce pb lors du démarrage de
l'application ?
A suivre,
Bien cordialement,
Vicnent Bonamy.

2018-06-26 9:41 GMT+02:00 devwald <notifications@github.com>:

**Comment by devwald** [comment]
J'ai cette erreur dans le log tomcat au démarrage de l'application : 

```
26-Jun-2018 09:54:13.957 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.14 (Debian)
26-Jun-2018 09:54:17.082 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2018-06-26 09:54:22,118 [localhost-startStop-1] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERROR: column am.amcanorder does not exist
  Position: 407
2018-06-26 09:54:22,119 [localhost-startStop-1] ERROR org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000299: Could not complete schema update
java.lang.NullPointerException
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.tool.hbm2ddl.DatabaseMetadata.getTableMetadata(DatabaseMetadata.java:129)
	at org.hibernate.cfg.Configuration.generateSchemaUpdateScript(Configuration.java:1133)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:212)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:178)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:503)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1750)
	at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:94)
	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:905)
	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:890)
	at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java:74)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:370)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:359)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:856)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
26-Jun-2018 09:54:25.664 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
26-Jun-2018 09:54:25.687 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
26-Jun-2018 09:54:25.692 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 11774 ms

```

**Comment by vbonamy** [comment]
Le "column am.amcanorder does not exist" proviendrait du fait que le
postgresql utilisé 'ne correspond pas' au driver utilisé.

Cette issue est donc liée à la modification du driver postgres dans
votre autre issue #2


2018-06-26 9:55 GMT+02:00 devwald <notifications@github.com>:

**Comment by devwald** [comment]
Merci.
C'était bien ça.
Bonne journée.
Cdt.
